[project]
name = "xlsx-clean"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Diaco Soltanpour", email = "dyaco8464@yahoo.com" }
]
dependencies = [
    "beaupy>=3.8.2",
    "nicegui>=2.5.0",
    "pandas>=2.2.2",
    "pywebview>=5.0",
    "pywin32>=306; sys_platform == 'win32'",
]
readme = "README.md"
requires-python = ">= 3.12"

[project.scripts]
xlsx-clean = "xlsx_clean.clean_cells:main"
xlsx-clean-web = "xlsx_clean.web_app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/xlsx_clean"]

[tool.hatch.build.targets.wheel.force-include]
"src/xlsx_clean/file_data.csv" = "xlsx_clean/file_data.csv"
"src/xlsx_clean/strings.txt" = "xlsx_clean/strings.txt"
"src/xlsx_clean/new_xslx.bat" = "xlsx_clean/new_xslx.bat"

[project.optional-dependencies]
desktop = [
    "pyinstaller>=6.0",
]
